</div> <!-- /container -->

<footer class="bg-danger text-white text-center py-4 mt-5 shadow-sm">
    <div class="container">
        <p class="mb-0">&copy; <?= date('Y') ?> <strong>Tandil Noticias</strong></p>
        <small class="d-block">Todos los derechos reservados</small>
    </div>
</footer>

<!-- Bootstrap JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="./js/main.js"></script>
</body>
</html>
