<nav class="navbar navbar-expand-lg navbar-dark bg-danger shadow-sm">
    <div class="container">
       <a class="navbar-brand fw-bold" href="<?= BASE_URL ?>">Tandil Noticias</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Alternar navegación">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <?php foreach ($categorias as $cat): ?>
                    <?php if ($cat->activa == 0) continue; // Omitir categorías inactivas ?>
                    <li class="nav-item">
                        <a class="nav-link" href="mostrarCategoria/<?= $cat->id_categoria ?>">
                            <?= htmlspecialchars($cat->nombre) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-4">
